#ifndef CONFIG_H
#define CONFIG_H

#define CFG_UHID_STOP_TIMEOUT_MS 100
#define CFG_KEYBOARD_VENDOR 0x046B
#define CFG_KEYBOARD_PRODUCT 0xFF10
#define CFG_KEYBOARD_NAME "sendkey virtual-keyboard"

#define CFG_DEFAULT_UHID_OPEN_DELAY_MS 100
#define CFG_DEFAULT_TAP_DURATION_MS 100
#define CFG_DEFAULT_TAP_INTERVAL_MS 50
#define CFG_DEFAULT_PRESS_DURATION_MS 100
#define CFG_DEFAULT_RELEASE_DURATION_MS 50

#endif // CONFIG_H
